;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2015/4/23 15:26:00

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1001=说明.html	; 简介
IDH_1003=部署-环境.html	; 环境
IDH_1004=部署-步骤.html	; 步骤
IDH_1005=部署-参数.html	; 配置参数说明
IDH_1007=接入配置-创建接入应用.html	; 创建接入应用AppCode
IDH_1008=接入配置-配置业务.html	; 配置业务CommandCode
IDH_1009=接入配置-配置业务字段信息.html	; 配置业务字段信息
IDH_1011=调用API说明-构造条件.html	; 构造条件
IDH_1012=调用API说明-基本查询.html	; 基本查询
IDH_1013=调用API说明-智能提示.html	; 智能提示
IDH_1014=调用API说明-热词查询.html	; 热词查询
IDH_1016=数据格式-推送格式.html	; 推送格式及api
IDH_1017=数据格式-FTP数据格式.html	; FTP数据格式
IDH_1018=数据格式- 服务数据格式.html	; 服务数据格式
