;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2015/4/23 15:26:00

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1001	1001	; 简介 说明.html
#define IDH_1003	1003	; 环境 部署-环境.html
#define IDH_1004	1004	; 步骤 部署-步骤.html
#define IDH_1005	1005	; 配置参数说明 部署-参数.html
#define IDH_1007	1007	; 创建接入应用AppCode 接入配置-创建接入应用.html
#define IDH_1008	1008	; 配置业务CommandCode 接入配置-配置业务.html
#define IDH_1009	1009	; 配置业务字段信息 接入配置-配置业务字段信息.html
#define IDH_1011	1011	; 构造条件 调用API说明-构造条件.html
#define IDH_1012	1012	; 基本查询 调用API说明-基本查询.html
#define IDH_1013	1013	; 智能提示 调用API说明-智能提示.html
#define IDH_1014	1014	; 热词查询 调用API说明-热词查询.html
#define IDH_1016	1016	; 推送格式及api 数据格式-推送格式.html
#define IDH_1017	1017	; FTP数据格式 数据格式-FTP数据格式.html
#define IDH_1018	1018	; 服务数据格式 数据格式- 服务数据格式.html
